# Generated by Django 5.1.1 on 2024-12-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pswd',
            field=models.CharField(max_length=128),
        ),
    ]
