# Generated by Django 5.1.5 on 2025-02-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0003_availability_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(default=2, limit_choices_to={'doc': True}, on_delete=django.db.models.deletion.CASCADE, to='Medi.user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medi.user'),
        ),
    ]
